language: csharp
solution: SmartContracts.NET/Strongforce.sln
sudo: required
dist: xenial
mono: none
dotnet: 2.2

install:
  - dotnet restore SmartContracts.NET/

script:
  - dotnet build SmartContracts.NET/
  - dotnet test SmartContracts.NET/StrongForce.Core.Tests/ --no-build --verbosity=normal
  - dotnet test SmartContracts.NET/StrongForce.Integrations.Cosmos.Tests/ --no-build --verbosity=normal