language: csharp
solution: SmartContracts.NET/Strongforce.sln
sudo: required
dist: xenial
mono: none
dotnet: 2.2

install:
  - pushd ..; git clone https://github.com/comrade-coop/wetonomy.git wetonomy; popd
  - dotnet restore src/

script:
  - dotnet build src/